### ISSUE TITLE
DLL factory not being called

### ISSUE THREAD

**Issue by FireHeartMaster** [spayne/soft_knuckles#3]
I followed all instructions in the readme, built the project changed .bat installation strings, ran it, and it seems the dll factory is not being called by Steam, so nothing happens after that (including not being able to use telnet to localhost 27015).

I also tried the sample driver from OpenVR, but for some reason all calls to `UpdateBooleanComponent` just return `VRInputError_InvalidHandle`, even with the original code version. I had already tried your driver before, but never could put it to work. I put some `DriverLog` calls inside some of the functions, including `HmdDriverFactory` and nothing comes from there, showing it's not being called.

Is there something I may be missing about the installation process?

**Comment by spayne** [comment]
The dll not being loaded is a super common/typical issue when getting started/setup. The good news is that it's always fixable.

Usually it's something wrong in the paths, so steamvr is looking in the wrong spot. Sometimes it's because steamvr has got itself into "safe mode" so it's not even looking, and most rarely the DLL is missing some dependencies so windows isn't able to load it.

* check the paths first *
The first thing to do is run a system report and look for some more information.   From the steam monitor (the little dialog box that says "SteamVR Beta 1.4.1"), the 3 horizontal bars on the top left is a menu, select that and then Create System Report.  From that you will get a window that includes "Logs".  

You are looking for a reference to soft_knuckles. e.g. something like: Unable to load driver soft_knuckles from C:\projects\soft_knuckles\soft_knuckles\bin\win64\driver_soft_knuckles.dll.

If you can find that message, copy and paste that path into a windows explorer and see if that file exists - it's a confusing path, but that's the first thing to check.   Let me know what you find here.

**Comment by spayne** [comment]
btw, I saw you post about the UpdateBooleanComponent returning VRInputError_InvalidHandle on the openvr issues before.  I think you said it was working at one point and then stopped working.  This suggests something changed in your environment - did something change? (did you do anything to your steam environment, move files around, mess with registry)...  Can you try the sample driver on a different or clean machine (e.g. a laptop you have hanging around?))

**Comment by FireHeartMaster** [comment]
Hey, thanks for your answer. I tried to see the logs and I get the error shown in the image below:
![error_soft_knuckles](https://user-images.githubusercontent.com/41326218/56566139-42c06580-65b2-11e9-90ba-01f8cb28a72b.png)

while my install_softknuckles_debug.bat contains the following: `"C:\Program Files (x86)\Steam\steamapps\common\SteamVR\bin\win64\vrpathreg.exe" adddriver C:\Users\eoctavioguimaraes\Downloads\soft_knuckles-master_\soft_knuckles-master\soft_knuckles
echo o | xcopy x64\Debug\soft_knuckles.dll soft_knuckles\bin\win64\driver_soft_knuckles.dll
`
I changed the "f" to "o" because the command window asked if I wanted to replace the previous file it had there, as you can check in the image below: 
![error_soft_knuckles_cmd](https://user-images.githubusercontent.com/41326218/56566009-0260e780-65b2-11e9-8df3-0940336bda56.png)

What is strange to me so far, is that the dll file is indeed in the specified location, actually, even when I try to move the soft_knuckles folder to the SteamVR\drivers folder and adding the path with vrpathreg I still get the same problem.

**Comment by FireHeartMaster** [comment]
About the UpdateBooleanComponent problem, the only thing I did was adding a new button to the sample driver, then it was working well. 

Satisfied enough with the result, I installed Steam in a fresh new machine and tried to load the same driver I had previously created in the other machine, for my surprise the driver was not working in this new machine.
As I could not figure out why, I came back to the previous computer where it worked, the driver still worked there. Then I added some lines where the code would create a file and write to it so I could check until what point the code could go. Even if it was working, a few rounds of closing and opening SteamVR again it started not working either (exactly that, I didn't change any other Steam files, just moved the sample driver folder to SteamVR\drivers folder and used vrpathreg). 

As it wasn't working anymore, I tried the original code from Valve's github and it continued not working.
Personally I suppose it's not being able to load because it's trying to use different bindings than those in the driver folder, but I'm not sure.

**Comment by FireHeartMaster** [comment]
I discovered that the dll was indeed missing dependencies. I used a program to check the dependency hierarchy and there were some missing. I think it's possibly due to my Visual Studio installation or even the system itself. 

The good news is that I had no problem installing soft knuckles driver to the new machine I mentioned above, it seems to work nicely and I can use the debug client to send commands to the controllers. 

Btw is there a way of changing the orientation of the controllers? Using your instructions I could change the controllers' positions and simulate button presses after having bound the inputs, but I couldn't see how to change the orientation. 
I saw your `send_request` function uses `VRSystem()->DriverDebugRequest` to send changes to the controllers, but I couldn't find anywhere how to use this function, the only place was here in your git. Do you know how I could use it to change controller orientation or if there is another method to do so?
I suppose I could try `vr::VRServerDriverHost()->TrackedDevicePoseUpdated` to do that, but, since your client code doesn't use it either to change positions, I feel it's not what I'm looking for.

**Comment by spayne** [comment]
Glad to hear you resolved the loading issue.  The symptoms you described - steamvr failing to load a correct path - is one I've seen before when loading debug dlls on a machine without visual studio installed.  So something isn't correct in your Visual Studio install.  I'm going to mark this issue as closed.

1/
Another comment I was going to make is that xcopy isn't used in install_softknuckles_debug.bat anymore - so you don't have the latest code.

2/
Regarding adding support for modifying the orientation - the short answer it doesn't appear I have support for that.  

To do it - you'll have to think about how you are going to specify the rotation.  
Then, add a new command to the debug handler here:
https://github.com/spayne/soft_knuckles/blob/06e12804b7bc83700ba3e5e312754fad32582afa/soft_knuckles_debug_handler.cpp#L278

something like
else if (tokens[0] == "ori")
{
   double x = atof(tokens[1].c_str());;
   double y = atof(tokens[2].c_str());;
   double z = atof(tokens[3].c_str());;

  m_device->qRotation = make_quaternion(x,y,z)
}

Unless you are sending raw quaternions, you'll need to write or find code to make a quaternion from 3 rotations.

**Comment by FireHeartMaster** [comment]
Thank you very much for your help, now everything seems to be working neat.

For the orientation of the controllers, I imagined I could use `DriverDebugRequest()` for that as for position changes. If that's not the case, I think I can manage to create a workaround using `vr::VRServerDriverHost()->TrackedDevicePoseUpdated()`

**Comment by spayne** [comment]
you are welcome.  Feel free to open up other issues - I marked the issue as closed as a positive thing: since the original loading issue was resolved.
