### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ghost** [spayne/soft_knuckles#5]
Does the driver still work for you ?
Cause not for me.

**Comment by spayne** [comment]
As far as I know it's still working and has been used as a starting point for a few other drivers    

Can you be more specific?  Did you get it working before and it stopped working?  Is SteamVR loading the driver at all?  Is the driver installed?  

FYI, Also there is another example driver I wrote that is simpler at https://github.com/spayne/right_hand_test  That one has a youtube intro that might help explain what to expect with installing and testing a steamvr driver.

**Comment by wqaxs36** [comment]
This one isn't working either.
I am trying to add finger control to my VR driver, so I added your code to mine.
But it's not working.
