### ISSUE TITLE
Soft knuckles not appearing in-game

### ISSUE THREAD

**Issue by jakecrowley** [spayne/soft_knuckles#7]
The soft knuckles driver and debug client works and appears in SteamVR Home, however the controllers do not appear in any game which supports the valve knuckles controllers (Aperature Hand Labs, The Lab, etc). I have a suspicion that it is because the game needs to detect the controllers as Valve Knuckles, however I do not have the correct model number to put into the OpenVR driver to test this theory.

**Comment by spayne** [comment]
I'll give the games you mentioned  a try later on today.  I'm glad that at least you got SteamVR Home working.

Usually issues with the hands not showing up has to do with 
1) bindings not being set properly or 
2) the game is looking at the device id directly which is what you are suggesting. In the past I've noticed this with Job Simulator but have not had issues with The Lab or Aperature Hand Labs.

I'll get back to you later.

**Comment by jakecrowley** [comment]
I should probably mention that I am using an Oculus Rift S, which may affect the game somehow (not detecting lighthouses?). I also tested the driver in Moondust, which is a known working game with your driver, with the same problem. I also noticed during my testing that I am only able to control the right soft knuckles controller from the debug client. If I try to enter a command such as 'l pos 0 0 0' the debug client does not print 'ok' and nothing happens. However, it works perfectly with the right controller.

**Comment by jakecrowley** [comment]
I noticed in the debug log that the games were using the legacy bindings, and it doesn't seem like there is much in the legacy bindings json file. Could this be the issue?

**Comment by jakecrowley** [comment]
I got it working! I had to go into the web binding interface and manually set the left and right skeletons, before the game would show the controllers. I was wrong in my last post, the binding files were fine, it was just the game not automatically setting up a configuration. 

![hand](https://user-images.githubusercontent.com/8465805/72043712-d8ef0580-327f-11ea-9ee9-7e110cda3e1d.png)

**Comment by spayne** [comment]
awesome!

**Comment by jakecrowley** [comment]
I seem to have everything working properly now, just one more thing, do you have any idea how I would go about controlling each finger individually without using pre-programmed bone positions like you have right now?

**Comment by meruune** [comment]
@jakecrowley 

> I seem to have everything working properly now, just one more thing, do you have any idea how I would go about controlling each finger individually without using pre-programmed bone positions like you have right now?

Ask there. 
Sorry i didnt wrote on reddit to you, 
but you know, school started again.

You can see on my reddit, that it is done,
But available only for a few people.
I think i could help you with that.

@spayne 
Thank you for a such thing.
I use kinect and arduino,
Made it controller driver, 
Gonna release someday.

DESU :)
